"use client";

import { useState } from "react";
import { Activity, Check, CircleHelp, RefreshCw, TriangleAlert } from "lucide-react";
import type { BlockMetrics } from "@/types/thermal";

type CheckState = "idle" | "starting" | "processing" | "completed" | "failed" | "no-response";
function readPersistence(value: unknown, path = "", depth = 0): number | null { if (depth > 6 || value == null) return null; if ((typeof value === "number" || typeof value === "string") && /persistence|consecutive|duration|hours|mean|average/i.test(path)) { const number = Number(value); return Number.isFinite(number) && number >= 0 && number <= 24 ? number : null; } if (typeof value !== "object") return null; for (const [key, child] of Object.entries(value as Record<string, unknown>)) { const found = readPersistence(child, `${path}.${key}`, depth + 1); if (found !== null) return found; } return null; }
function verdict(hours: number) { return hours >= 6 ? "Persistent heat" : hours >= 3 ? "Sustained heat" : "Brief exposure"; }
function readableDate(date: string | null) { return date ? new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" }).format(new Date(`${date}T00:00:00Z`)) : "the latest completed day"; }

export function ChronicHeatCheck({ block }: { block: BlockMetrics }) {
  const [state, setState] = useState<CheckState>("idle"); const [hours, setHours] = useState<number | null>(null); const [date, setDate] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const thresholdC = 32;
  async function poll(activityId: string, attempt = 0): Promise<void> { if (attempt >= 120) { setState("no-response"); return; } await new Promise(resolve => window.setTimeout(resolve, 5000)); try { const response = await fetch(`/api/fortyguard/status?kind=heatmap&activityId=${encodeURIComponent(activityId)}`); const payload = await response.json() as { status?: string; result?: { stats?: unknown }; error?: string; message?: string | null }; if (!response.ok || payload.error) throw new Error(payload.error ?? "Persistence status check failed."); if (payload.status === "Completed") { const result = readPersistence(payload.result?.stats); if (result === null) throw new Error("FortyGuard completed the check but did not return a readable persistence metric."); setHours(Math.round(result * 10) / 10); setState("completed"); return; } if (payload.status === "Failed") throw new Error(payload.message ?? "FortyGuard could not complete the persistence check."); await poll(activityId, attempt + 1); } catch (cause) { setError(cause instanceof Error ? cause.message : "Persistence analysis failed."); setState("failed"); } }
  async function start() { setState("starting"); setHours(null); setError(null); try { const response = await fetch("/api/fortyguard/chronic", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ latitude: block.lat, longitude: block.lng, thresholdC }) }); const payload = await response.json() as { activityId?: string; date?: string; error?: string }; if (!response.ok || !payload.activityId || payload.error) throw new Error(payload.error ?? "Could not start the persistence analysis."); setDate(payload.date ?? null); setState("processing"); void poll(payload.activityId); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not start the persistence analysis."); setState("failed"); } }
  const busy = state === "starting" || state === "processing";
  return <section className="mt-4 rounded-lg border p-3.5" style={{ borderColor: "var(--border)", background: "var(--surface)" }}>
    <div className="flex items-start gap-3"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full font-mono text-[10px] text-accent-strong" style={{ background: "var(--accent-dim)" }}>2</span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h3 className="text-[13px] font-bold text-paper">Was this heat short-lived or persistent?</h3><span title="This checks the longest uninterrupted stretch above 90°F / 32°C in the small area around this selected cell, using the latest complete UTC day."><CircleHelp className="h-3.5 w-3.5 text-slate" /></span></div><p className="mt-0.5 text-[11px] leading-relaxed text-slate">A hot moment may pass quickly. Longer heat can be more useful to prioritise for investigation.</p></div></div>
    <button type="button" onClick={start} disabled={busy} className="mt-3 flex w-full items-center justify-center gap-2 rounded-md border py-2.5 text-[12px] font-bold disabled:cursor-wait disabled:opacity-60" style={{ borderColor: "var(--accent-border)", color: "var(--accent-strong)", background: "var(--accent-dim)" }}>{busy ? <RefreshCw className="h-3.5 w-3.5 animate-spin" /> : <Activity className="h-3.5 w-3.5" />}{state === "starting" ? "Starting heat-duration check…" : state === "processing" ? "Measuring time above 90°F…" : state === "completed" ? "Refresh heat-duration result" : "Measure how long the heat lasted"}</button>
    {state === "processing" && <p className="mt-2 text-[10px] leading-relaxed text-slate" aria-live="polite">We are measuring the longest uninterrupted time the area stayed above 90°F. This can take a few minutes.</p>}
    {state === "completed" && hours !== null && <div className="mt-3 rounded-md border p-3" style={{ borderColor: "var(--accent-border)", background: "var(--accent-dim)" }}><div className="flex items-center justify-between gap-3"><span className="font-mono text-[10px] tracking-wide text-accent-strong uppercase">{verdict(hours)}</span><Check className="h-3.5 w-3.5 text-accent-strong" /></div><p className="mt-1 text-[14px] font-semibold text-paper">The area stayed above 90°F for {hours.toFixed(1)} hours without a break.</p><p className="mt-1 text-[10px] leading-relaxed text-slate">Based on {readableDate(date)}. This measures heat duration in a small local area; it is not a health outcome or proof of cause.</p></div>}
    {state === "no-response" && <p className="mt-3 flex gap-1.5 text-[11px] leading-relaxed text-slate"><TriangleAlert className="mt-0.5 h-3.5 w-3.5 shrink-0" />Still processing. Try again later to resume this check.</p>}
    {error && <p className="mt-3 flex gap-1.5 text-[11px] leading-relaxed" style={{ color: "#e36b5d" }}><TriangleAlert className="mt-0.5 h-3.5 w-3.5 shrink-0" />{error}</p>}
  </section>;
}
