import type { BlockMetrics } from "@/types/thermal";
import { round } from "@/lib/utils";

/**
 * Deterministic offsets used to build a nearby-block temperature spread
 * around a given average. Fixed, not random — every reload of the demo
 * shows the same numbers.
 */
const OFFSETS = [
  -3.2, -2.5, -1.9, -1.3, -0.8, -0.3, 0.2, 0.7, 1.2, 1.8, 2.4, 3.1, 3.9, 4.8,
];

function spread(center: number, n: number): number[] {
  return OFFSETS.slice(0, n).map((o) => round(center + o, 1));
}

/**
 * DEMO DATA — deterministic, hand-authored, not sourced from FortyGuard
 * or any live measurement. Used whenever FORTYGUARD_API_KEY is absent.
 * Values are plausible for the named neighborhoods but are illustrative,
 * not measured.
 */
export const DEMO_BLOCKS: BlockMetrics[] = [
  {
    id: "nyc-183",
    city: "New York City",
    neighborhood: "Mott Haven, Bronx",
    lat: 40.8093,
    lng: -73.9227,
    temperature: 97.4,
    nearbyAverage: 92.6,
    surfaceTemperature: 129,
    nearbySurfaceTemperature: 112,
    treeCanopyPct: 8,
    nearbyTreeCanopyPct: 24,
    imperviousSurfacePct: 71,
    nearbyImperviousSurfacePct: 44,
    buildingDensity: 0.62,
    nearbyBuildingDensity: 0.51,
    windMph: 2.1,
    nearbyWindMph: 5.8,
    historicalAnomaly: 4.3,
    nearbyBlockCount: 12,
    distribution: spread(92.6, 12),
  },
  {
    id: "nyc-047",
    city: "New York City",
    neighborhood: "Long Island City, Queens",
    lat: 40.7447,
    lng: -73.9485,
    temperature: 94.1,
    nearbyAverage: 91.0,
    surfaceTemperature: 121,
    nearbySurfaceTemperature: 108,
    treeCanopyPct: 11,
    nearbyTreeCanopyPct: 19,
    imperviousSurfacePct: 64,
    nearbyImperviousSurfacePct: 49,
    buildingDensity: 0.58,
    nearbyBuildingDensity: 0.49,
    windMph: 3.4,
    nearbyWindMph: 4.9,
    historicalAnomaly: 2.8,
    nearbyBlockCount: 10,
    distribution: spread(91.0, 10),
  },
  {
    id: "nyc-210",
    city: "New York City",
    neighborhood: "Upper West Side, Manhattan",
    lat: 40.787,
    lng: -73.9754,
    temperature: 86.9,
    nearbyAverage: 89.3,
    surfaceTemperature: 96,
    nearbySurfaceTemperature: 104,
    treeCanopyPct: 31,
    nearbyTreeCanopyPct: 21,
    imperviousSurfacePct: 38,
    nearbyImperviousSurfacePct: 52,
    buildingDensity: 0.55,
    nearbyBuildingDensity: 0.58,
    windMph: 5.2,
    nearbyWindMph: 4.4,
    historicalAnomaly: -2.1,
    nearbyBlockCount: 11,
    distribution: spread(89.3, 11),
  },
  {
    id: "nyc-072",
    city: "New York City",
    neighborhood: "East New York, Brooklyn",
    lat: 40.6659,
    lng: -73.8848,
    temperature: 95.8,
    nearbyAverage: 91.7,
    surfaceTemperature: 124,
    nearbySurfaceTemperature: 109,
    treeCanopyPct: 9,
    nearbyTreeCanopyPct: 22,
    imperviousSurfacePct: 68,
    nearbyImperviousSurfacePct: 46,
    buildingDensity: 0.49,
    nearbyBuildingDensity: 0.44,
    windMph: 2.8,
    nearbyWindMph: 5.1,
    historicalAnomaly: 3.6,
    nearbyBlockCount: 13,
    distribution: spread(91.7, 13),
  },
  {
    id: "nyc-301",
    city: "New York City",
    neighborhood: "Astoria, Queens",
    lat: 40.7644,
    lng: -73.9235,
    temperature: 90.2,
    nearbyAverage: 89.8,
    surfaceTemperature: 103,
    nearbySurfaceTemperature: 101,
    treeCanopyPct: 18,
    nearbyTreeCanopyPct: 20,
    imperviousSurfacePct: 50,
    nearbyImperviousSurfacePct: 48,
    buildingDensity: 0.47,
    nearbyBuildingDensity: 0.46,
    windMph: 4.6,
    nearbyWindMph: 4.9,
    historicalAnomaly: 0.6,
    nearbyBlockCount: 9,
    distribution: spread(89.8, 9),
  },
  {
    id: "chi-014",
    city: "Chicago",
    neighborhood: "Little Village",
    lat: 41.8477,
    lng: -87.7137,
    temperature: 96.5,
    nearbyAverage: 91.2,
    surfaceTemperature: 127,
    nearbySurfaceTemperature: 110,
    treeCanopyPct: 7,
    nearbyTreeCanopyPct: 19,
    imperviousSurfacePct: 73,
    nearbyImperviousSurfacePct: 47,
    buildingDensity: 0.54,
    nearbyBuildingDensity: 0.46,
    windMph: 3.9,
    nearbyWindMph: 6.6,
    historicalAnomaly: 4.7,
    nearbyBlockCount: 14,
    distribution: spread(91.2, 14),
  },
  {
    id: "chi-088",
    city: "Chicago",
    neighborhood: "Englewood",
    lat: 41.7791,
    lng: -87.6438,
    temperature: 95.0,
    nearbyAverage: 90.4,
    surfaceTemperature: 122,
    nearbySurfaceTemperature: 107,
    treeCanopyPct: 12,
    nearbyTreeCanopyPct: 23,
    imperviousSurfacePct: 66,
    nearbyImperviousSurfacePct: 45,
    buildingDensity: 0.41,
    nearbyBuildingDensity: 0.4,
    windMph: 5.1,
    nearbyWindMph: 7.4,
    historicalAnomaly: 4.0,
    nearbyBlockCount: 12,
    distribution: spread(90.4, 12),
  },
  {
    id: "chi-152",
    city: "Chicago",
    neighborhood: "Pilsen",
    lat: 41.8563,
    lng: -87.6577,
    temperature: 92.3,
    nearbyAverage: 89.9,
    surfaceTemperature: 112,
    nearbySurfaceTemperature: 103,
    treeCanopyPct: 15,
    nearbyTreeCanopyPct: 21,
    imperviousSurfacePct: 58,
    nearbyImperviousSurfacePct: 49,
    buildingDensity: 0.52,
    nearbyBuildingDensity: 0.48,
    windMph: 4.8,
    nearbyWindMph: 6.0,
    historicalAnomaly: 2.0,
    nearbyBlockCount: 10,
    distribution: spread(89.9, 10),
  },
  {
    id: "chi-203",
    city: "Chicago",
    neighborhood: "Lincoln Park",
    lat: 41.9214,
    lng: -87.6513,
    temperature: 84.6,
    nearbyAverage: 87.1,
    surfaceTemperature: 92,
    nearbySurfaceTemperature: 99,
    treeCanopyPct: 34,
    nearbyTreeCanopyPct: 24,
    imperviousSurfacePct: 36,
    nearbyImperviousSurfacePct: 47,
    buildingDensity: 0.49,
    nearbyBuildingDensity: 0.5,
    windMph: 8.2,
    nearbyWindMph: 6.9,
    historicalAnomaly: -2.2,
    nearbyBlockCount: 11,
    distribution: spread(87.1, 11),
  },
  {
    id: "chi-041",
    city: "Chicago",
    neighborhood: "Bridgeport",
    lat: 41.8339,
    lng: -87.6519,
    temperature: 90.8,
    nearbyAverage: 90.5,
    surfaceTemperature: 105,
    nearbySurfaceTemperature: 104,
    treeCanopyPct: 19,
    nearbyTreeCanopyPct: 20,
    imperviousSurfacePct: 51,
    nearbyImperviousSurfacePct: 50,
    buildingDensity: 0.45,
    nearbyBuildingDensity: 0.44,
    windMph: 6.1,
    nearbyWindMph: 6.3,
    historicalAnomaly: 0.5,
    nearbyBlockCount: 9,
    distribution: spread(90.5, 9),
  },
  {
    id: "la-029",
    city: "Los Angeles",
    neighborhood: "Boyle Heights",
    lat: 34.0339,
    lng: -118.2098,
    temperature: 101.2,
    nearbyAverage: 96.0,
    surfaceTemperature: 134,
    nearbySurfaceTemperature: 116,
    treeCanopyPct: 6,
    nearbyTreeCanopyPct: 17,
    imperviousSurfacePct: 75,
    nearbyImperviousSurfacePct: 51,
    buildingDensity: 0.48,
    nearbyBuildingDensity: 0.43,
    windMph: 1.8,
    nearbyWindMph: 3.9,
    historicalAnomaly: 4.8,
    nearbyBlockCount: 13,
    distribution: spread(96.0, 13),
  },
  {
    id: "la-116",
    city: "Los Angeles",
    neighborhood: "South Los Angeles",
    lat: 33.9908,
    lng: -118.2827,
    temperature: 99.8,
    nearbyAverage: 95.3,
    surfaceTemperature: 129,
    nearbySurfaceTemperature: 114,
    treeCanopyPct: 8,
    nearbyTreeCanopyPct: 18,
    imperviousSurfacePct: 70,
    nearbyImperviousSurfacePct: 50,
    buildingDensity: 0.44,
    nearbyBuildingDensity: 0.41,
    windMph: 2.2,
    nearbyWindMph: 4.1,
    historicalAnomaly: 4.0,
    nearbyBlockCount: 12,
    distribution: spread(95.3, 12),
  },
  {
    id: "la-204",
    city: "Los Angeles",
    neighborhood: "Arts District, Downtown",
    lat: 34.0403,
    lng: -118.2354,
    temperature: 97.9,
    nearbyAverage: 95.1,
    surfaceTemperature: 122,
    nearbySurfaceTemperature: 111,
    treeCanopyPct: 10,
    nearbyTreeCanopyPct: 15,
    imperviousSurfacePct: 66,
    nearbyImperviousSurfacePct: 55,
    buildingDensity: 0.6,
    nearbyBuildingDensity: 0.55,
    windMph: 2.9,
    nearbyWindMph: 3.8,
    historicalAnomaly: 2.4,
    nearbyBlockCount: 10,
    distribution: spread(95.1, 10),
  },
  {
    id: "la-058",
    city: "Los Angeles",
    neighborhood: "Silver Lake",
    lat: 34.0869,
    lng: -118.2702,
    temperature: 90.1,
    nearbyAverage: 93.4,
    surfaceTemperature: 98,
    nearbySurfaceTemperature: 108,
    treeCanopyPct: 27,
    nearbyTreeCanopyPct: 16,
    imperviousSurfacePct: 42,
    nearbyImperviousSurfacePct: 54,
    buildingDensity: 0.46,
    nearbyBuildingDensity: 0.48,
    windMph: 4.5,
    nearbyWindMph: 3.6,
    historicalAnomaly: -3.0,
    nearbyBlockCount: 9,
    distribution: spread(93.4, 9),
  },
];

export function getBlock(id: string): BlockMetrics | undefined {
  return DEMO_BLOCKS.find((b) => b.id === id);
}

export function blocksForCity(city: BlockMetrics["city"]): BlockMetrics[] {
  return DEMO_BLOCKS.filter((b) => b.city === city);
}
